# Generated by Django 3.0.14 on 2021-07-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
        ('course', '0020_leaderboard_leaderboardstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='assigned_course',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='leaderboardstudents',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='canvas.CanvasCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboardstudents',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardstudents',
            name='team',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
