# Generated by Django 3.0.14 on 2021-07-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_event_type'),
        ('course', '0021_auto_20210702_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_streak', models.IntegerField(default=0)),
                ('team_tokens', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canvas.CanvasCourse')),
            ],
        ),
    ]
